FROM node:20.14.0-bullseye as base

ENV WORKDIR_APP /app

WORKDIR ${WORKDIR_APP}

# Copia todos los archivos necesarios al contenedor
COPY package*.json ./
COPY tsconfig*.json ./

COPY nest-cli.json ./
COPY . .

# Instala las dependencias
RUN npm install && npm install -g @nestjs/cli --verbose

# Exponer el volumen
VOLUME [${WORKDIR_APP}]

# Comando para iniciar la aplicación
CMD ["npm", "run", "start:prod"]