FROM node:20.14.0-bullseye as base

ENV WORKDIR_APP /app

WORKDIR ${WORKDIR_APP}
COPY package*.json ./
COPY tsconfig*.json ./
COPY nodemon.json ./
COPY nest-cli.json ./

RUN cd ${WORKDIR_APP}

RUN npm set registry http://nexus.prod.uci.cu/repository/npm-proxy/

RUN npm install && npm install -g @nestjs/cli --verbose


VOLUME [${WORKDIR_APP}]


CMD ["npm run start:dev"]